name: Omni Quickstart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Omni CLI
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/omni-network/omni/main/scripts/install_omni_cli.sh | sh -s

      - name: Scaffold a new project
        shell: bash
        run: |
          mkdir my-omni-dapp
          cd my-omni-dapp
          omni developer new

      - name: Start local devnet
        shell: bash
        run: |
          cd my-omni-dapp
          omni devnet start &
          sleep 30  # Wait for the devnet to start

      - name: Deploy contracts
        shell: bash
        run: |
          cd my-omni-dapp
          export PORTAL_ADDRESS=0xb835dc695c6bfc8373c0d56973b5d9e9b083e97b
          export GLOBAL_GREETER_ADDRESS=0x8464135c8F25Da09e49BC8782676a84730C318bC
          export PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
          forge script DeployGlobalGreeter --broadcast --rpc-url http://localhost:8000 --private-key $PRIVATE_KEY
          forge script DeployRollupGreeter --broadcast --rpc-url http://localhost:8001 --private-key $PRIVATE_KEY
          forge script DeployRollupGreeter --broadcast --rpc-url http://localhost:8002 --private-key $PRIVATE_KEY

      - name: Perform Cross-Chain Greet
        shell: bash
        run: |
          cd my-omni-dapp
          export PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
          cast send 0x8464135c8F25Da09e49BC8782676a84730C318bC 'greet(string)' 'Yay in 3 minutes!' --private-key $PRIVATE_KEY --rpc-url http://localhost:8001 --value 1ether

      - name: Check the Greet
        shell: bash
        run: |
          cd my-omni-dapp
          result=$(cast call 0x8464135c8F25Da09e49BC8782676a84730C318bC "lastGreet():(uint64,uint256,uint256,address,address,string)" --rpc-url http://localhost:8000)
          echo "Result: $result"
          if [[ $result != *"Yay in 3 minutes!"* ]]; then
            echo "Test failed: Greet message not found"
            exit 1
          fi

